name: "Financial Data Template"
description: "Template for generating financial and banking data"
version: "1.0.0"

tables:
  - table_name: accounts
    description: "Bank accounts"
    columns:
      - name: account_id
        type: int
        constraints: [PK]
        rule:
          type: range
          min: 100000000
          max: 999999999
        description: "Unique account identifier"

      - name: account_number
        type: str
        constraints: [UNIQUE]
        rule:
          type: pattern
          regex: "^[0-9]{10,12}$"
        sensitivity: FINANCIAL
        description: "Account number"

      - name: account_type
        type: str
        rule:
          type: choice
          value: ["checking", "savings", "credit", "investment"]
          probabilities:
            checking: 0.4
            savings: 0.3
            credit: 0.2
            investment: 0.1
        description: "Type of account"

      - name: balance
        type: float
        rule:
          type: range
          min: 0.00
          max: 1000000.00
        description: "Current account balance"

      - name: customer_id
        type: int
        constraints: [FK]
        description: "Reference to customer"

      - name: opened_date
        type: date
        rule:
          type: date_range
          start: "2010-01-01"
          end: "2024-12-31"
        description: "Date account was opened"

      - name: status
        type: str
        rule:
          type: choice
          value: ["active", "inactive", "closed", "frozen"]
          probabilities:
            active: 0.7
            inactive: 0.15
            closed: 0.1
            frozen: 0.05
        description: "Account status"

  - table_name: customers
    description: "Bank customers"
    columns:
      - name: customer_id
        type: int
        constraints: [PK]
        rule:
          type: range
          min: 1
          max: 1000000

      - name: first_name
        type: str
        rule: first_name
        description: "Customer first name"

      - name: last_name
        type: str
        rule: last_name
        description: "Customer last name"

      - name: email
        type: str
        rule:
          type: email
        sensitivity: PII
        description: "Customer email address"

      - name: phone
        type: str
        rule:
          type: phone_number
        sensitivity: PII
        description: "Customer phone number"

      - name: date_of_birth
        type: date
        rule:
          type: date_range
          start: "1950-01-01"
          end: "2005-12-31"
        sensitivity: PII
        description: "Customer date of birth"

      - name: ssn
        type: str
        rule:
          type: pattern
          regex: "^[0-9]{3}-[0-9]{2}-[0-9]{4}$"
        sensitivity: CONFIDENTIAL
        description: "Social Security Number"

      - name: annual_income
        type: float
        conditional_rules:
          - condition:
              column: date_of_birth
              operator: age_greater_than
              value: 65
            rule:
              type: range
              min: 20000
              max: 80000
          - condition:
              column: date_of_birth
              operator: age_between
              value: [25, 65]
            rule:
              type: range
              min: 30000
              max: 200000
        description: "Annual income"

    foreign_keys:
      - parent_table: customers
        parent_column: customer_id
        child_column: customer_id

relationships:
  - type: one_to_many
    parent: customers
    child: accounts
    description: "One customer can have multiple accounts"
